### ISSUE TITLE
avro schema Serialization, deserialization & validation.

### ISSUE THREAD

**Issue by Big-Vi** [memphisdev/memphis.net#105]
Serialization, deserialization, and Validation for avro schema needs to be added.

Related to:
https://github.com/memphisdev/memphis/issues/1061
https://github.com/memphisdev/memphis/pull/1107

**Comment by bazen-teklehaymanot** [comment]
Hi @Big-Vi , we will start working on this once the active PR is merged to Memphis. Thanks!

**Comment by Big-Vi** [comment]
@bazen-teklehaymanot This PR `https://github.com/memphisdev/memphis/pull/1107` is merged now. 🎉

**Comment by bazen-teklehaymanot** [comment]
Great! I think we can close this issue until the end of this week.
