### ISSUE TITLE
Run for loop of produce messages with http request from rest gateway

### ISSUE THREAD

**Issue by shohamroditimemphis** [memphisdev/memphis.net#106]
a. Please run a code that includes infinite for loop that call to single produce endpoint from rest gateway.
b. When the for loop run and produce a lot of messages to specific station - please remove the station from the ui and check that there are no errors like that
CreateHandleMessage - produce: memphis: no responders available for request
c. Also check it with produce from .Net sdk and also with produce http request from rest gateway

we check it because in go sdk I need to add locks and to fix it when we remove a station, so we need to check it also in .Net sdk

Here my example in go to run infinite loop:
```
package main

import (
	"bytes"
	"fmt"
	"net/http"
	"time"
)

func main() {
	endpoint := "http://localhost:4444/stations/test1/produce/single"
	interval := 1 * time.Second

	// Infinite loop to make the HTTP requests
	for {
		err := makeHTTPRequest(endpoint)
		if err != nil {
			fmt.Println("Error making HTTP request:", err)
		}

		time.Sleep(interval)
	}
}

func makeHTTPRequest(url string) error {
	payload := []byte(`{"key": "value"}`)

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(payload))
	if err != nil {
		return err
	}

	// Set the "Authorization" header with the Bearer token
	req.Header.Set("Authorization", "Bearer "+"token")
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("Received non-OK response: %d", resp.StatusCode)
	}

	return nil
}
```

**Comment by bazen-teklehaymanot** [comment]
I tested the scenario using both the SDK, and the REST api. This is the current behaviour:

**REST**
- Produces a message to existing station, and if the station doesn't exist the station gets created then the message is published

**SDK**
- The producer is created, and during initialization if the the station doesn't exist it is created
- While infinitely producing messages, if the station is deleted from the UI, then the `Produce` function throws `no responders available for request` exception.

My question: when producing a message should the SDK ensure the station exists? and if a station doesn't exist then similar to the REST api the station should be created?

@shohamroditimemphis

**Comment by shohamroditimemphis** [comment]
Hi, great thanks.
In  the rest it is working as expected.
In sdk:
In golang I need to add some changes in order to fix the error :no responders available for request. You can see it in pr:https://github.com/memphisdev/memphis.go/pull/106/files. Please add the fixes accordingly in .Net sdk.

Regarding your question - in sdk in produce function in background we create producer and station. If the station does not exist we create a station.

please pay attention to this line in pr:
c.removeSchemaUpdatesListener(update.StationName)

I think that you should add it also in .Net sdk and after that check the scenario with infinitely producing messages and delete a station. You should no longer receive the error no responders available for request @bazen-teklehaymanot

**Comment by bazen-teklehaymanot** [comment]
Thanks for clarifying @shohamroditimemphis!
