### ISSUE TITLE
Feature: Validate message before producer to producing [protobuf]

### ISSUE THREAD

**Issue by elchinmemphis** [memphisdev/memphis.net#3]
In the scope of implementation of schemaverse feature on client.SDK, Producer is expected to able to validate message based on the **protobuf schema** of station.

These schemas of station for producer is pushed by memphis-broker and stored in in-memory storage(ConcurrentDictionary), so that when Producer want to producing a message to memphis-broker, it needs to validate the message based on schema of station.

What TODO: **protobuf schema parsing** and **validation logic** need to be implemented.

For more references: Look at other Memphis.SDK implementations - [Go](https://github.com/memphisdev/memphis.go), [Python](https://github.com/memphisdev/memphis.py), [Javascript](https://github.com/memphisdev/memphis.js)

**Comment by bazen-teklehaymanot** [comment]
@elchinmemphis I'll start working on this

**Comment by bazen-teklehaymanot** [comment]
@elchinmemphis I couldn't find open-source .NET library that helps with schema aware payload parsing and validation for protobuf. Google.Protobuf and protobuf-net(contains a branch under development for this use-case) are among the libraries I checked. If you happed to know other libraries that can help here or suggest other approach please let me know.

**Comment by yanivbh1** [comment]
@bazen-teklehaymanot can't be achieved with the mentioned libs? another alternative, we can for now start without runtime schema changes.

**Comment by idanasulinmemphis** [comment]
Closing this one, will be released on the next version of the SDK
