### ISSUE TITLE
Add ability to produce more types when schema is not enforced

### ISSUE THREAD

**Issue by shay23b** [memphisdev/memphis.net#37]
When Schemaverse is not enforced we want to be able to produce Protobuf message, JSON, GraphQl message, as well as the standard types

**Comment by bazen-teklehaymanot** [comment]
@shay23b  the `ProduceAsync` method accepts byte array as an argument, I think that would be sufficient to send the different data types in the absence of schema.

**Comment by shay23b** [comment]
@bazen-teklehaymanot all the other SDKs accept all types mentioned above
