### ISSUE TITLE
Remove tenant name from requests in sdk

### ISSUE THREAD

**Issue by shohamroditimemphis** [memphisdev/memphis.net#77]
1. create producer
2. destory producer
3. create station
4. destroy station
5. create consumer 
6. destroy consumer
7. attach schema
8. deattach schema
9. Remove the function get tenant name 

https://github.com/memphisdev/memphis.go/pull/98

**Comment by bazen-teklehaymanot** [comment]
This issue is related to #65, #70. Since the PR was never merged I'll close this issue along with the PR(#70)
