### ISSUE TITLE
Interfaces for main classes for tests purposes

### ISSUE THREAD

**Issue by ofekca** [memphisdev/memphis.net#82]
Currently it is not possible to create mocks for test purposes for the main classes of the SDK such as MemphisConsumer, MemphisProducer and MemphisClient.

I would like to be able to write unit tests and mock those classes. In order to do so, it is required that the classes would have interfaces. for example:
`MemphisClient` should implement The `IMemphisClient` interface.

Example code of a beginning of a test that I would like to write but can't with the current SDK.

`     var memphisClientMock = new Mock<IMemphisClient>();

        var msg = new Msg()
        {
            Data = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new MemphisAuthor()
            {
                Uid = "uid1"
            })),
            Header = new MsgHeader()
            {
                { "source", "source1" }
            }
        };
        
        var memphisMessage = new MemphisMessage(msg, memphisClientMock.Object, "", 1);
        var msgHeader = new Msg()
        .....

`

**Comment by yanivbh1** [comment]
Thank you for the feature request @ofekca !
We are on it. Adding @idanasulinmemphis and @bazen-teklehaymanot

**Comment by bazen-teklehaymanot** [comment]
Thank you @ofekca, we appreciate your suggestions and will add this. We expect it to be available next week.
