### ISSUE TITLE
Connection Hangs Indefinitely Even When Timeout Set

### ISSUE THREAD

**Issue by JarrodJ83** [memphisdev/memphis.net#88]
Using the docker-compose from the getting started guide along with the sample code provided below from this repo I am unable to connect to Memphis running in docker. The connection never times out even though I've set `TimeoutMs`. Could you point me in the right direction here? Memphis seems to be up and running and the ports are open. Would help if I could get an exception to throw to tell me why it's unable to connect. Thanks in advance!

```
using Memphis.Client;

try
{
    var options = MemphisClientFactory.GetDefaultOptions();
    options.Host = "localhost";
    options.Username = "root";
    options.Password = "memphis";
    options.TimeoutMs = 1000;    

    var memphisClient = await MemphisClientFactory.CreateClient(options);
    
}
catch (Exception ex)
{
    Console.Error.WriteLine("Exception: " + ex.Message);
    Console.Error.WriteLine(ex);
}
```

**Comment by JarrodJ83** [comment]
Looking at the logs from the Memphis broker it seems its failing authentication but no exceptions are thrown client side: 
`authentication error - User "root$1"`

**Comment by bazen-teklehaymanot** [comment]
Hi @JarrodJ83 , this issue is resolved on the SDK, and it will be available on the next release next week.

**Comment by JarrodJ83** [comment]
Out of curiosity, what was the issue and fix?
