### ISSUE TITLE
Typo in DLS Prefix?

### ISSUE THREAD

**Issue by turulix** [memphisdev/memphis.net#98]
I'm not 100% sure, but in every other SDK the DLS_PREFIX is `$memphis_dls_` in this one its:
https://github.com/memphisdev/memphis.net/blob/c3d9e328344fdd1ab6d46d84d2eae48cfc3c6eed/src/Memphis.Client/Constants/MemphisConstants.cs#L29

**Comment by bazen-teklehaymanot** [comment]
Thank you for pointing it out @turulix, we will fix it.
